### ISSUE TITLE
Keypad smaller in landscape mode

### ISSUE THREAD

**Issue by ce7726** [thanksmister/android-mqtt-alarm-panel#80] opened 2018-12-22 02:39 UTC
When in portrait mode, keypad is big and easy to use, when in landscape mode, keypad is smaller and difficult to press digits on 7 inch screen for example.

Is it possible to have the same keypad than the one in portrait mode

By the way, it would be nice if the red ALARM TRIGGERED keypad screen had those 4 dots that indicate how many digits have been pressed.

**Comment by thanksmister** [comment] 2019-01-07 15:23
It's a lot of work, but its possible.  I have to experiment with 7" tablet.  Each tablet has a different resolution, so its not just the screen size that changes the display.  Going fullscreen would probably be the best solution.

**Comment by thanksmister** [comment] 2019-01-07 19:53
duplicate of #66

**Closed by thanksmister** 2019-01-07 19:53 UTC
Labels: enhancement, feature request
