### ISSUE TITLE
App becomes really slow when night mode is active

### ISSUE THREAD

**Issue by matthijsberg** [thanksmister/android-mqtt-alarm-panel#109] opened 2019-09-19 20:48 UTC
When I enable night mode in the app (mqtt messages are configured) the app becomes unworkable slow and I see the screen flip between a dark and a bit darker tint about every second. App is so slow it's hard to get to the control panel and change it back (need to kill the app, restart and quickly get to the panel).

**To Reproduce**
1. Go to 'settings/ display'
2. Turn on "Use Night Mode"
3. Go back to the front page

**Expected behavior**
to be as responsive as without "Use Night Mode" on.

**Smartphone (please complete the following information):**
 - Device: Huawei MediaPad M5 lite 10
 - OS: Android 8.0.0 (kernel 4.4.23)
 - Version 0.8.6 b5

**Comment by thanksmister** [comment] 2019-09-20 12:06
Sounds like you may have something going on with the brightness setting.  Do you have the brightness setting on in the app settings?  Check under Display, scroll down and uncheck it if you have it on.    I am not able to reproduce the issue on a Nexus 5 with Android 9 or Fire OS 7 device.

**Comment by thanksmister** [comment] 2019-09-26 12:17
No follow-up, so closing for now

**Closed by thanksmister** 2019-09-26 12:17 UTC

**Comment by FuzzyMistborn** [comment] 2019-12-06 04:26
I'm seeing similar issues.  The app seems to keep opening/closing and is basically unworkable.  Noticed it on my nexus 7 before the battery crapped out and seeing it now on my Fire 7 tab.  Let me know if you need other info.
