### ISSUE TITLE
Hass page reloads every time it regains focus

### ISSUE THREAD

**Issue by NickChamberlin** [thanksmister/android-mqtt-alarm-panel#35] opened 2018-07-20 12:42 UTC
When the screen is turned on the Hass page does a complete reload, when you swipe from the alarm panel to the Hass page it does a reload of the page. If the Hass page has already been loaded once since the alarm panel app has started, it shouldn't reload the Hass page.

**Comment by thanksmister** [comment] 2018-07-20 16:56
Can you provide the steps to reproduce and also some information about your device and what you are running.  Also if the application is always in the foreground, are you using the device screen saver or letting the device sleep.   Be as accurate as you an so I can reproduce the issue.

**Comment by NickChamberlin** [comment] 2018-07-24 18:58
Video might help: https://photos.app.goo.gl/x5i1PjFiWy4VyQfT6

Whenever the app gains focus, the Hass page reloads. Going to the Android home screen then pulling the alarm panel back up causes the Hass page to reload. When the screen turns off, then you turn it back on, the Hass page reloads.

**Comment by thanksmister** [comment] 2018-07-24 19:35
Got it, thanks.  I will try to address this in the next release.

**Comment by thanksmister** [comment] 2018-07-26 15:55
There is one issue caused by removing the refresh of the HASS page on view.  If you load the HASS page successfully but restart your HASS server, the webpage breaks with an error and there is no way to refresh the page.   You have to go into the settings, than return in order to refresh the web page or you need to have the controls active (in the settings) which display at the bottom of the platform web page view and have buttons to refresh.

**Comment by NickChamberlin** [comment] 2018-07-27 01:57
The new lovelace interface they're phasing in has a refresh button in the 3 dots menu at the top right, would that not work? Another idea if that doesn't work, could you have the controls at the bottom of the screen come up when you swipe up from the bottom of the screen?

**Comment by thanksmister** [comment] 2018-07-27 19:31
I attempted to show bottom controls that you can swipe away or hide, they will periodically appear unless you turn off the settings for showing the bottom bar on the platform page.   This gives you a chance to refresh if you do have issues.   I have created a beta program for the next release due to the amount of changes.  You can join the beta program if you wish to test the next version before it's released to production here: https://play.google.com/apps/testing/com.thanksmister.iot.mqtt.alarmpanel

**Comment by thanksmister** [comment] 2018-08-16 12:05
This should be fixed in the latest version v0.8.2 Build 7

**Closed by thanksmister** 2018-08-16 12:05 UTC
Labels: bug
