### ISSUE TITLE
Unable to set alarm state with latest beta version

### ISSUE THREAD

**Issue by samueldumont** [thanksmister/android-mqtt-alarm-panel#39] opened 2018-08-08 11:41 UTC
Hi,

I'm currently installing the alarm panel at home and wanted to use the new features in the beta version. In the stable version, communication is going flawlessly from the control panel to the mqtt and I see the changes reflected in home assistant.

However, on the beta (0.8.2) it does not seem to work. I see states changes when triggered in HA, but no communication seems to come from the app through the home/alarm/set channel.

I tried to download the code and debug it directly on my phone but my Android development skills are rather limited. If you need data (bug reports, dumps, etc), I will happily provide them.

I can translate to French if you need it, I can take some time to do it :)

**Comment by thanksmister** [comment] 2018-08-08 12:30
I will take a look and see if their is a problem.  Thanks so much for the offer to translate into French, that would be great.  I will get back to you soon with the mqtt issue.

**Comment by thanksmister** [comment] 2018-08-08 12:59
I downloaded the latest beta version and set the alarm from HASS first and then set the alarm from the application.  Both are in sync with each other.  Here is what I have for my configuration yaml:

```
alarm_control_panel:
  - platform: manual_mqtt
    state_topic: home/alarm
    command_topic: home/alarm/set
    pending_time: 60
    trigger_time: 1800
    disarm_after_trigger: false
    delay_time: 30
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0
    armed_away:
      pending_time: 60
      delay_time: 30
```

All I did to setup the beta was enter the ip address of my HASS install, I didn't change the port or any other settings.  Can you double check that you have the correct ip address in the beta (though I am sure you probably upgraded so it should be the same).  Perhaps there is a glitch migrating from the previous version to the beta.   The ip address should be without the prefix (http://) and the port.

**Comment by thanksmister** [comment] 2018-08-08 14:02
Also check that your Alarm Command and Alarm Topic are "home/alarm/set" and "home/alarm" in the MQTT settings of the application.   The port should be 1883 unless your setup is different.

**Comment by thanksmister** [comment] 2018-08-08 14:30
No, the problem is in the application.   The beta version isn't sending the mqtt command correctly to the mqtt hass broker.  Sorry for misleading you, I had accidentally installed the production version and it worked, but the beta version isn't working as expected.   I will issue a fix today hopefully, thanks for your patience.

**Comment by samueldumont** [comment] 2018-08-08 14:33
Ok thanks a lot, I'm not crazy then :) Thanks for you quick response. I'm working on the translation, it should be done relatively quickly.

**Comment by thanksmister** [comment] 2018-08-08 14:33
I don't know if you are crazy :) but I know you are correct.

**Comment by thanksmister** [comment] 2018-08-08 15:45
Ok, look for a new updated with a fix for this issue.  I will close this now unless you have further issues.   Thanks!

**Closed by thanksmister** 2018-08-08 15:45 UTC

**Comment by samueldumont** [comment] 2018-08-09 09:02
It's working perfectly, thank you very much !
