### ISSUE TITLE
Various issues after upgrade to v1.1.0 Build 8

### ISSUE THREAD

**Issue by FireWizard52** [thanksmister/android-mqtt-alarm-panel#162] opened 2021-05-17 15:59 UTC
Hi.

This post covers several issues/bugs I discovered recently.

Used Phone: Motorola G9 PLUS
Android version: 10
Intended use: MQTT server (Mosquitto) to Node-Red (so no Home Assistant)

1.
After an automatic upgrade from version 1.0.2-beta.0 to version1.1.0-beta.8 (or is it build 8) which was done probably 2 days ago,
I was automatically greeted with a "Light grey" screen with the text "SYSTEM DISABLED".

First of all, I'm surprised that a new beta release is automatically  installed.

Touching (Clicking) that screen does not give any reaction and it showed only the time and date in the top right corner and the wheel widget (settings) in the lower right corner As I configured also the "Panic" widget, that one was available as well.

From a previous initial install, I new I had to "activate" this app, by sending a MQTT message with msg.topic = "home/alarm" and   msg.payload = "disarmed"; to the app.  Then the green field with text "SYSTEM DISARMED" (or something, as I have my phone configured for Dutch)

I took an old phone:

Phone: Motorola G3 (3rd generation)
Android: 6.0.1

Clicking on the grey  field gives useful hints, such as Setting up the device, MQTT server and alarm information.
So it points you clearly to the settings screen. 
However this has not been the case on the phone, where the MQTT Alarm panel already has been setup.

Is this by design or a bug, that I have to reactivate the app by sending data from the application. (Node-Red)

2. On the G9 phone touching the Theme function causes a crash of the app. However if I open the app again it is opening with the new theme,
This is not the case with the newly installed version on the old phone.

3. . On the G9 phone touching the Advanced Setting function causes a crash of the app.

Removal en Re-installation off the app does not solve the problem.

4. The new functionality of multiple external webpages is nice for e.g camera's, but I see that the webpage with the camera is loaded but there is a turning wheel that goes up to 80%, while the screen is okay.

So checking further.

Regards

**Comment by thanksmister** [comment] 2021-05-17 16:15
The app has always been in beta and this app was distributed on a slow rollout.  We do this because its not possible to test all devices and configurations as we develop new features.   You are not locked into only running this version, you can revert back to any of the previous versions available in the releases section (just turn off auto update).  

I tested both the theme and the advanced settings, but could not reproduce the crashes.    I checked Firebase and I see one issue on a Galaxy S8  running Android 9 with 1.1.0 Build 8 (11008).  I do not have crashes for a G9 device, maybe you can verify which OS you are running. 

You normally do not have to update the remote MQTT data after an update, but this update included a database migration, so it needs to receive some new data to function fully, usually this happens right away if the data was retained.  

For camera performance, you are unfortunately stuck with whatever version of WebView you have on your device.   This component is response for all the web rendering and its part of the Android SDK.   You may be able to update this component, but that's really the only way. 

Sorry for the rough transition, but I do appreciate your feedback.  Again, you can revert to an older version (manually installing the ADB and making sure auto-update for apps is not set) if you need.  

Thanks!

**Comment by FireWizard52** [comment] 2021-05-17 16:37
Hi @thanksmister 

Thank you for your quick response. This is very appreciated.

I know I can revert back to a previous release. That is easy, but it does not help to bring this excellent app forward.

I tried to delete the complete app, including cache, etc., but  after re-installation it still finds old data, like pin-code and other app settings.
I would like to try a complete new and clean installation from scratch in order to find out if the issues are related to the phone model or to anything in the database introduced by an earlier version.
Do you know, how to remove everything regarding the database of the panel?

FYI the OS is Android 10, kernel 4.14.117-perf+
Level of security patch March 1, 2021. System update 2021-04-01

**Comment by thanksmister** [comment] 2021-05-17 16:41
It's not possible to have the same data if you have deleted the application, this clears the local store as well.   If you use the Android device to uninstall the app, that clears all data, there is no way that it does not.

**Comment by FireWizard52** [comment] 2021-05-17 17:01
@thanksmister 

Sorry to say, I always thought so, that if you completely uninstall an app, by stopping the app , deleting the user data, cache memory and at last delete the app, that everything was gone.

However, every new installation gives me the old configuration.
I see it immediately, as the widget for "Panic" is displayed. So it is stored somewhere.

**Comment by thanksmister** [comment] 2021-05-17 17:03
That doesn't mean its the old configuration, what do you have in your settings for your MQTT information?   Having panic button is just true/false toggle.

**Comment by thanksmister** [comment] 2021-05-17 17:06
These are the default settings on a new install:

![Screenshot_1621271107](https://user-images.githubusercontent.com/142340/118528593-e68c8900-b718-11eb-968b-2ea7c98f0816.png)

I this is not what you see, then do you have two versions of same app installed?  The app is not responsible for clearing the settings, the device is.  It's not a feature of the app to clear settings.

**Comment by thanksmister** [comment] 2021-05-17 17:09
First time on main screen:

![Screenshot_1621271348](https://user-images.githubusercontent.com/142340/118529075-7cc0af00-b719-11eb-83d8-ad3b4ee8ef23.png)

**Comment by thanksmister** [comment] 2021-05-17 17:12
I tested https://github.com/thanksmister/android-mqtt-alarm-panel/releases/tag/v1.1.0.8 on a clean device, it seems to have the correct behavior for first launch, though missing the alert dialog.   Uninstalling previous version removes all it's data as well.

**Comment by FireWizard52** [comment] 2021-05-17 17:13
@thanksmister 

Thank you very much for your support and the screenshots. I saw this screens, when I installed on my old phone for the first time.
When I do a new install, I can only log-in with my own pin code and not with the default 1234 and I directly see my own configuration and not the default.

So it seems that somewhere is old data.

**Comment by thanksmister** [comment] 2021-05-17 17:14
That is unfortunate and I am not able to address that type of issue since clearing the data is the job of the device operating system.

**Comment by FireWizard52** [comment] 2021-05-17 17:17
@thanksmister 

I thank you so far with all the support and I will continue to search for the root cause.

If I find it, I will keep you informed.

Keep up the good work,

Regards

**Comment by thanksmister** [comment] 2021-05-17 17:18
Well, having old data is an annoyance but you can just manually reset it.  It should not be the cause of the crashes you reported.  Check your advanced settings on new install, check dark theme.   These are the most concerning.

**Comment by FireWizard52** [comment] 2021-05-17 17:52
@thanksmister,

I have found the cause.
The  phone has been configured to make back-ups to Google-Drive and obviously the app got the data from there.
I have now disabled this backup and removed that back-up  also from Google-Drive.

This option, you can find at:
Settings ==> System ==> Advanced ==> Back-up

Deleted the stored data, cache and finally the app. After re-installation it came in the default configuration, as shown in your screenshot.

Thank you very much for your confirmation that it wasn't the app. Focusing on the device pointed in that direction.
But obviously the backed-up data caused the crash.

I will continue testing now and keep you informed.

Regards

**Comment by FireWizard52** [comment] 2021-05-18 19:48
I continued testing of the app..

So far I have discovered the following:

1. After configuration the screen still shows "System Disabled".
First, after a command send to the app, the green field with "System disarmed" will appear

As I believe this is by design, it is a suggestion to add that to the README.

2. Advanced Settings is okay, but toggling the "Theme", causes the app to crash in 70% of all cases.
However the action is carried out.

3. As we had in 1.0.2-beta.0 the issue with the "Panic" button solved, we have a non-working "Panic" button again.
The published topic has changed. That is okay, but the payload is an empty string, instead of the expected string "PANIC".

4. The camera stream in the additional webpages are working fine now, without stopping the blue turning wheel at 80%.

I will continue testing, but this is what I have so far.

Regards

**Comment by thanksmister** [comment] 2021-05-18 20:02
I found the issue with PANIC and will work on a fix for that.   I have had a hard time getting the theme change to work for some reason, I will take a look again to see what's the issue.  It's kind of a destructive process as it needs to rebuild the Activity window.  

```
After configuration the screen still shows "System Disabled".
First, after a command send to the app, the green field with "System disarmed" will appear
```

Yeah good point about adding this to the documentation.   I don't seem to have this issue though with Home Assistant, the alarm state seems to be retained and broadcasts when connecting to the MQTT broker.

**Comment by FireWizard52** [comment] 2021-05-18 20:08
@thanksmister 

> Yeah good point about adding this to the documentation. I don't seem to have this issue though with Home Assistant, the alarm state seems to be retained and broadcasts when connecting to the MQTT broker.

In that case you build up the communication automatically. I will have a look to introduce that in Node Red as well.

Thanks so far.

**Comment by thanksmister** [comment] 2021-05-19 11:50
I am going to publish an update today that hopefully addresses the crash on theme change and fixes the panic feature.   I have noticed on my Fire OS 7 device that each time in the morning when the app changes from dark mode to light, the app crashes, but its not a crash, more like the app tries to restart the main activity, but is put into the background on the device.

**Comment by FireWizard52** [comment] 2021-05-19 12:07
@thanksmister 

Thanks for your efforts,
I will test it this afternoon or evening

Regards

**Comment by FireWizard52** [comment] 2021-05-19 14:55
@thanksmister 

I started testing with version v1.1.0-beta.9 and can confirm, that toggling the "Theme" multiple times did not crash the application. So this seems to be solved.

Also activating the "Panic" button results in the described action, as in the README.

I discovered also, that you are working on the README.md file. There are still some errors in it. I will check it and will come back with my remarks.

I have found the following (not specific for this release):

> However, if you want to send the alarm code with a command, the alarm panel will send the payload as JSON, which you will need to listen for and manually handle to parse out the command and the code value

> If you wanted to send the error that an invalid code was entered to disarm or arm the alarm, you would send the following JSON formatted payload on the event topic

> There is an option called Remote Code that will send both the alarm state and the code entered when arming or optionally disarming the alarm to your MQTT broker. The payload will be sent as JSON. This requires extra work on your part to parse the code and command paylaod from the JSON paylaod using your available platform tools. Here is an example JSON payload of an alarm command with the code:

{
  "command": "<my command>",
  "code": "<my pin>"
}

When choosing to use this feature, the security code you set within the application settings is only used to access the settings, is is no longer used to arm or disarm the system. When entering a code to arm or disarm your system, the code will now be sent to the remote server along with the command as a JSON payload.

The server must respond with either a alert message or return the new alarm state. You must validate the alarm code on the server and either update the alarm state or return an alert message that the code is invalid.

If you enter a wrong pin code, you will not receive  a MQTT message. Only if you send the correct pin code you will receive the JSON payload:

{
  "command": "<my command>",
  "code": "<my pin>"
}

I think the intention is that you always receive a payload and that the code contains the pin code, either correct, incorrect or empty.

As long as no payload is send the connected application (HASS, Node-Red) is unable to check the payload and to respond with an event message "invalid_code_provided"
In case of an incorrect payload a notification on the screen is given, so I wonder if someone needs an additional notification on the apps screen. It is up to you to decide.

Regards

**Comment by thanksmister** [comment] 2021-05-19 16:42
What we did was integrate with Alarmo component which handles errors and additional MQTT states (night, custom bypass).  So if the user choose to use the remote option, a JSON payload is always sent to the server, with COMMAND value and CODE value which must be parsed if you are not using Alarmo.   

So for Node you would get the JSON and if you wanted to validate the code, you would have to parse that out of the payload and do some server-side computation to validate if the code was valid.  You would be responsible for sending back the error codes yourself.    The application will display an appropriate message (though not yet translated into all languages). 

However, this is only if you want to use remote code, if you are not using it, you can just send string values for each payload as before and will not receive JSON values.   

I have not yet built out examples to do remote code without Alarmo integration, but I will eventually handle everything in the documentation without requiring Alarmo, for Node as an example where Alarmo does not exist.    

If you want to update and clarify the documentation,  you can do a pull request just for the documentation and update it, that would be a great help for me.  Even if you have examples for Node, that would be great as I want the app to be for all platforms that support MQTT.

**Comment by thanksmister** [comment] 2021-05-19 16:47
> If you enter a wrong pin code, you will not receive a MQTT message. Only if you send the correct pin code you will receive the JSON payload:

The message that is received from incorrect PIN code is sent back to the application from the MQTT broker if you want the application to display the appropriate error message.  Maybe this part is confusing.   The command/code JSON will always be sent but its up to the broker to validate the code and return error messages

**Comment by thanksmister** [comment] 2021-05-19 16:50
> The server must respond with either a alert message or return the new alarm state. You must validate the alarm code on the server and either update the alarm state or return an alert message that the code is invalid.

The server (broker) should do the work to validate codes for Node, and if the code does not match pre-existing known code value, send back the appropriate MQTT error message to the application.   So what I mean by this is that the platform has to do the work on the incoming JSON payload to validate codes sent from the application and the platform just send either update the state of the alarm or send out a valid MQTT message with appropriate error code back to the application.   

This is only if user has selected to use Remote Code in the settings.  I think I have been too vague on these descriptions, without examples of what would be needed on the server, it's hard to tell what's going on.   Maybe I need flow charts or something.

**Comment by FireWizard52** [comment] 2021-05-19 16:57
@thanksmister

I think there is some misunderstanding.

You wrote:

> So for Node you would get the JSON and if you wanted to validate the code, you would have to parse that out of the payload and do some server-side computation to validate if the code was valid. You would be responsible for sending back the error codes yourself. 

The JSON response is only send if you select in "Advanced Setting" "Remote Code"
However this JSON response with the "command" and the "code" is only sent, if the pin code is correct.
If you enter the wrong pin code nothing is sent. So there is very little to parse or to respond with an error.
If you receive a code, it is always valid.

Another issue is that in the same topic "home/alarm/set", payloads are sent both as string and as JSON object.
Without the pin code, it is always a string, with the pin code it is a JSON object  and the "Panic" button is also always a string.
This makes it much more complicated.

I suggest to use either a string or a JSON, but not both for the same topic (home/alarm/set).
An option is to enter also the pin code in case of PANIC, but that is in such case not desired. So maybe publish it under another topic as it has been previously.

I will definitely make a pull request regarding the README.md

Regards

**Comment by thanksmister** [comment] 2021-05-19 17:15
> However this JSON response with the "command" and the "code" is only sent, if the pin code is correct.
> If you enter the wrong pin code nothing is sent. So there is very little to parse or to respond with an error.
> If you receive a code, it is always valid.

No, that is not at all how it works.  The application does not validate the code if you select remote code in the settings.  The code and the command are sent as JSON always.  The server validates the code.   The only time the code would be used if remote code option is active is for opening the settings.    The app has no way of knowing the remote codes, this is why it sends your code to the server with the command if remote code is active.      

What happens in Home Assistant is the Alarmo integration knows the codes, it receives the JSON and it validates the code, if code is invalid, a error message will be sent back to the application.   This is how its designed for use with remote code. 

If you do not select the remote code option, everything works exactly as it didi before, the payload is a string value as outlined in the documentation.  Only the command is sent, not the code and not JSON.  Just a single string value.

**Comment by thanksmister** [comment] 2021-05-19 17:22
> I suggest to use either a string or a JSON, but not both for the same topic (home/alarm/set).

The reason we use both is because we want to be compatible with the MQTT Manual component that ships with Home Assistant, the original reason the app was built.   It is only because we added "advanced" features and compatibility with Alarmo that we offer "Remote Code" options and send JSON.    There are many users, probably the majority that still use the MQTT manual integration for their home assistant alarm control.   So we have to support it still.

**Comment by FireWizard52** [comment] 2021-05-19 17:56
@thanksmister 

Thank you for all your posts. I can follow it, but I do not  think you understand what I mean.

You wrote:

> No, that is not at all how it works. The application does not validate the code if you select remote code in the settings. The code and the command are sent as JSON. The server validates the code and handles error or updates state of alarm.

YES. That is how it should work, at least what I expect, how it should work. But it does not.

I fully understand your explanation.

> The reason we use both is because we want to be compatible with the MQTT Manual component that ships with Home Assistant, the original reason the app was built. It is only because we added "advanced" features and compatibility with Alarmo that we offer "Remote Code" options and send JSON. There are many users, probably the majority that still use the MQTT manual integration for their home assistant alarm control. So we have to support it still.

Agree, we should not break the function, because of existing users.

But let me explain, how this app v1.1.0 Build 9 works in my case:

1. I have configured in "Advanced Setting", "Remote Code" to be active.

That would mean that I should receive in the topic: home/alarm/set a JSON response with command and code.

2. If I activate e.g. ARM_Home, the app ask me for a (the) pin code.

If the code is wrong, I see a pop-up line with a text: "Code is invalid, Try again".

This should not happen, according to your explanation.

3. In this case no MQTT command has been sent. So there is nothing to parse.

If I send the correct pin  code will be sent code, the JSON.

So obviously the app does some checking of the pin code, contrary to what you explained and I would expect.
So this must be a bug regarding this "Remote Code".

Also in the Alarmo panel you should see that, that in case of a wrong pin code nothing is received.
Has this been tested?

Sorry to keep nagging you, but this is something in your app,
Have a look to it.

Then I will look to the README.md

Regards

**Comment by thanksmister** [comment] 2021-05-19 19:23
What you are reporting would be a bug, but I do not see that behavior.   I will test it again to verify, but the behavior should be as I have described.

**Comment by FireWizard52** [comment] 2021-05-19 19:31
@thanksmister

I really have that behaviour.
Be aware, that I do not communicate with HASS, but with Node Red.

Regards

**Comment by thanksmister** [comment] 2021-05-19 19:35
Without remote, disarming the alarm sends only `DISARM`.   With remote code option active, it sends `{"command":"DISARM","code":"3355"}` to disarm the alarm.    Maybe we have some confusing about arming vs disarming?   Are you trying to send the code to arm the alarm as well?

**Comment by FireWizard52** [comment] 2021-05-19 19:37
Yes, I do

Both in case of Arming and disarming, I send the code.

**Comment by thanksmister** [comment] 2021-05-19 19:42
When arming with remote code active, it sends payload as `{"command":"ARM_HOME","code":"3355"}`.  Without remote code active, arming sends just the string value `ARM_HOME`.   That is the default behavior.  

What I see as a possible issue is that when remote code and require code to arm on both active, the interface for entering the code is incorrect.  It is set to only accept 4 digits, it should be the same as disarm with remote code, showing a dialog with a submit button for a code up to 8 digits in length. 

![Screenshot_1621452867](https://user-images.githubusercontent.com/142340/118874254-11b1dc80-b8c1-11eb-9dc7-fd2df60db41b.png)

However, I did not find any issue with the behavior if you are just sending 4 digit codes remotely to arm or disarm the alarm.  The behavior is correct.

**Comment by thanksmister** [comment] 2021-05-19 19:43
I have to fix the issue so that when using remote code and send code to arm we use the correct bottom sheet with the send code key button.   I could not reproduce an issue sending only a string when remote code was active.  That behavior seems to be fine.   Perhaps its with a certain mode like arming away or night?

**Comment by FireWizard52** [comment] 2021-05-19 20:12
@thanksmister 

Some other issues that I found:

1, First screen in Settings:

Require Disarming Code
Require the the code to disarm the alarm

Require Arming Code
Require the the code toarm the alarm

In both case the the.

However I cannot find the file, where these texts are stored.

About half of the texts are not translated to Dutch.
If you need support for that, feel free to contact me.

**Comment by thanksmister** [comment] 2021-05-19 20:26
Hey, thanks, the files are stored in a .xml file under the res folder.  There are strings for every language.  I can update the bugs.   Yeah I have added a lot of new strings that are missing translations.  Here are the folders that hold all translations:
 
<img width="1047" alt="Screen Shot 2021-05-19 at 5 25 45 PM" src="https://user-images.githubusercontent.com/142340/118879576-445ed380-b8c7-11eb-8adc-53b0eb9326b5.png">

**Comment by FireWizard52** [comment] 2021-05-19 21:29
@thanksmister,

Hi, thanks. I have found the various texts.
Imho it are not that much.
I can do it, but previous translations have been made by Gerben Bol, I saw, and I do not want to interfere with his work.
Is he stil active? And/or is he still doing it?

Your point of view?

**Comment by thanksmister** [comment] 2021-05-19 21:30
Go for it, everyone can contribute and I appreciate all the help I can get!!

**Comment by thanksmister** [comment] 2021-05-20 12:52
I think for being consistent when remote code is active, we should send the PANIC command in the same JSON format:

`{"command":"PANIC","code":""}`

I am leaving the code empty because there is no requirement to enter a code to do a panic or silent alarm.

**Comment by FireWizard52** [comment] 2021-05-20 14:17
Agree, good idea.

**Comment by thanksmister** [comment] 2021-05-20 19:24
I have a new release but only from the github release section, this one contains the fixes as well as the new JSON for panic button if user has remote code active. 


https://github.com/thanksmister/android-mqtt-alarm-panel/releases/tag/v1.1.1.0

**Comment by FireWizard52** [comment] 2021-05-21 17:41
@thanksmister 

I discovered the following:

1. In Advanced Settings" "Remote Code" enabled.

So we send a JSON command, including  the command, e.g. ARM_HOME or ARM_AWAY and a code.
If the code is accepted by the application it is handled accordingly. If the code is wrong, the application sends a JSON response {"event": "invalid_code_provided"}
So far so good.

But

2. If we send a command (ARM_HOME or ARM_AWAY), but we do not enter a code a string ARM_AWAY or ARM_HOME will be sent, instead of a JSON command as follows:
{"command":"ARM_HOME","code":""} or {"command":"ARM_AWAY","code":""}

What the alarm panel expects in this case is a JSON response as follows:

topic: home/alarm/event
payload: {"event": "no_code_provided"}

To be persistent, I suggest to send also in case of an empty code a command in JSON format instead of a string.

**Comment by thanksmister** [comment] 2021-05-21 17:45
> 1. If we send a command (ARM_HOME or ARM_AWAY), but we do not enter a code a string ARM_AWAY or ARM_HOME will be sent, instead of a JSON command as follows:
>    {"command":"ARM_HOME","code":""} or {"command":"ARM_AWAY","code":""}
> 
> What the alarm panel expects in this case is a JSON response as follows:
> 
> topic: home/alarm/event
> payload: {"event": "no_code_provided"}
> 
> To be persistent, I suggest to send also in case of an empty code a command in JSON format instead of a string.

The rule should apply that we cannot send empty code, not allowed from application.  If you have remote code set or require code to arm/disarm, no empty codes should be allowed.  This will prevent user from sending empty strings.   We can check this at application level and save a trip to server.

**Comment by FireWizard52** [comment] 2021-05-21 18:52
@thanksmister 

> The rule should apply that we cannot send empty code, not allowed from application. If you have remote code set or require code to arm/disarm, no empty codes should be allowed. This will prevent user from sending empty strings. We can check this at application level and save a trip to server.

It will not only save a trip to the server, but also the effort of checking for empty code and returning the JSON  response "no_code_provided". 

Good idea.

**Comment by thanksmister** [comment] 2021-05-21 19:11
There is a still a chance that user has not setup remote code and sends only the string command, the server should handle this error with `no_code_provided` response.  Though this is edge case.

**Comment by thanksmister** [comment] 2021-05-21 19:14
New pre-release build https://github.com/thanksmister/android-mqtt-alarm-panel/releases/tag/v1.1.1.1

**Comment by FireWizard52** [comment] 2021-05-21 19:23
@thanksmister 

> There is a still a chance that user has not setup remote code and sends only the string command, the server should handle this error with no_code_provided response. Though this is edge case.

If I understand it correctly, that, if a user has not setup "Remote Code", no code will be sent. Then only the string command will be sent. That is correct. The server will not receive a code and so will not be able to check any code. So will not send "no_code_provided" response.  So you can skip that. Will never happen.

**Comment by thanksmister** [comment] 2021-05-21 19:25
It does happen in Home Assistant with Alarmo because sending a command as non-json returns the no code error.  But again, this is because of user error, not setting remote code in the app.

**Comment by FireWizard52** [comment] 2021-05-21 19:26
Okay, I was not aware of that.

**Comment by thanksmister** [comment] 2021-05-21 19:27
I guess they parse it regardless of it being json or now.  So if you have server logic similar for Node, then it would be an error, again this is user error.

**Comment by FireWizard52** [comment] 2021-05-21 19:29
Alright, I installed the new release and tested it.

It works as expected. /
Thanks for the quick reasponse.

**Comment by thanksmister** [comment] 2021-05-27 14:11
Can we close this ticket?

**Comment by FireWizard52** [comment] 2021-05-27 14:33
@thanksmister 

I think we can close this ticket. I have not discovered any other issue.
I'm working, but have not finished yet, on the new Dutch translations, as well I have made a small correction in the README file.
You will receive a PR for it.

Thanks so far, for you quick response.

Regards

**Closed** 2021-05-27 21:31 UTC
Labels: bug
