### ISSUE TITLE
Disarming doesn't always bring up 'Green padlock / Disarmed screen'

### ISSUE THREAD

**Issue by jaburges** [thanksmister/android-mqtt-alarm-panel#108] opened 2019-08-11 02:25 UTC
**Describe the bug**
Usually when testing and rapid disarming (by entering the code quickly, but successfully) instead of bringing up the green circle screen with 'System Disarmed' it remains on the red circle with System Armed Away.

**To Reproduce**
Armed Away
Disarm by entering code quickly

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
Tested on Fire HD 8 Tablet
Huawei tablet 
(both with same results)

**Additional context**
swiping to browser, or closing and reopening the app corrects the state

**Comment by mikkel-esp** [comment] 2019-09-09 20:02
I am seeing the same behavior.

 **Describe the bug**
Disarming (by entering the code) instead of bringing up the green circle screen with 'System Disarmed' it remains on the red circle with System Armed Away.

**To Reproduce**
Steps to reproduce the behavior:
Armed Away
Disarm 

**Expected behavior**
Disarm screen after disarming


**Smartphone (please complete the following information):**
Huawei tablet

**Additional context**
Closing and reopening the app or going to the setup of MQTT  corrects the state

**Comment by thanksmister** [comment] 2019-09-09 20:28
You can check the logs to see what your broker sent, sounds like it is not sending the correct response back to the application.

**Comment by mikkel-esp** [comment] 2019-09-09 20:42
In my case it is sporadic - it sometimes work.

broker traffic
home/alarm/set DISARM
home/alarm disarmed

Let me know if it is something else you are looking for.

Thanks

**Comment by thanksmister** [comment] 2019-09-10 12:35
When you disarm the alarm from the Android application is sends an MQTT message to your broker (I am assuming this is Home Assistant with Mosquitto).   It is your broker that must send out the message that the alarm is disarmed.   The application must be active, meaning not in the background and the device must have wifi connectivity) in order to receive the message from the broker.   

Since you say this is sporadic, my guess is that there is a connectivity issue between the broke and the client.   Check that the broker is in fact sending out the correct message and that the data is received in the application.   This is something you can easily test by using HA to arm and disarm your alarm from the HA alarm control panel and then observing the running application.   

During the times you experience a disconnect between the broker and client, check the settings and logs of the application to verify it has received the message from the broker at the same time it was sent from HA, if there is no message received, then this is an issue with your broker or network.

**Comment by repjas** [comment] 2020-08-01 20:20
Hi

First of all, thank you for an amazing application. This is exactly what I needed and it looks very nice.

I also encounter the problem described above. It sometimes happens, sometimes not and indeed i noticed it first after adding the TTS "alarm disarmed" by MQTT to the panel.

Could it be that it maybe doesn't handle well 2 simultaneous MQTT messages (the alarm/state: disarm and alarmpanel/command: speak)? I have no knowledge on this, so just a guess.

**Comment by thanksmister** [comment] 2020-08-02 13:45
I think it could be that while its processing TTS, it is not processing other background tasks.  I have not had a chance to investigate this on my own device.

**Comment by Hini2001** [comment] 2020-11-21 15:46
Hello,

i would say this APP is amazing and really what i need.

But now my problem:

I ran IOBROKER on a Raspi with the MQTT Adapter as Broker.
I would like to use your app, but i have the same problem.

When the system is DISARMED, everything is well. In IOBROKER under objects SET is DISARMED.
When I change to something else, the state SET is correctly changed an the app will show the right status.

NOW: When I want to DISARM, the state in IOBROKER is correctly changed to DISARM. But the App remains on ARMED.
After closing and reopening the correct state is shown (DISARMED).

Under IOBROKER the DEBUG log shows the change with the ACK-Flag true.
The LOGFILE in the App is completely EMPTY.

Is there a thing I could do? Because your App is AMAZING (and I am using the Wallpanel app as well on other Tablets in my house).

Excuse my bad englisch. I am from Germany.

Greetings

**Comment by thanksmister** [comment] 2020-11-21 15:50
The alarm only reacts to the MQTT alarm sate you send back.  You must mirror the MQTT state of your server by sending out the MQTT state change to the alarm panel.  I does not know the state of your server, it subscribes to topics to receive the state.  Take a look at the documentation, and the states the Home Assistant server will send back.  Send DISARM from the application should return "disarmed" message back after your server state changes.

**Comment by Hini2001** [comment] 2020-11-21 18:15
Thabk very very much. That worked perfect. Now i know which state i have Set. Perfect. Absolutely. Thank you alot.

**Closed** 2021-05-27 14:16 UTC
Labels: investigate
