### ISSUE TITLE
Random minimize

### ISSUE THREAD

**Issue by mvoosten** [thanksmister/android-mqtt-alarm-panel#81] opened 2018-12-23 21:33 UTC
Have no clue why it happens.. have a clean android install and only MQTT running. Sometimes out of the blue I get a last event message (same as when starting the app, since I use tts and the message states disarmed by voice) and when I look I will find MQTT alarm panel running in the background with the launcher on the foreground.

**Comment by thanksmister** [comment] 2019-01-07 15:06
Not sure, a possible crash. What device do you have?

**Comment by mvoosten** [comment] 2019-01-07 15:15
Samsung Galaxy S3 running LineageOS.
Also happened with such stock OS. However with stockOS voice notifications don't work. 
It's not crashed,  it still runs minimized on the background when it happens.

**Comment by thanksmister** [comment] 2019-01-07 15:16
well, something is making it to go into the background, if its not a crash then your system is putting the app into the background.  If you have stock os and no TTS, then make sure you have TTS installed on device and works

**Comment by mvoosten** [comment] 2019-01-07 18:55
It's weird also have a  Galaxy S8 and tab S2. The S8 works with TTS, the Tab S2 doesnt
. Both using Google TTS same as with the Galaxy S3, though both the S8 and Tab S2 are recent android versions.

**Comment by thanksmister** [comment] 2019-01-27 15:49
Try turning off night mode if its active,  I have been seeing the same behavior when the night mode changes.

**Comment by thanksmister** [comment] 2019-01-29 12:47
There are also reports of Samsung devices minimizing full screen apps randomly: https://forums.androidcentral.com/samsung-galaxy-s7/665032-apps-keep-minimizing-s7.html.  I am still investigating if its night mode.  I can reproduce the minimizing issue on my Fire tablet 7 after a couple of days, it just suddenly decides to minimize the app but its still running in the background.   I think this may have something to do with the sleep mode of the device, but its difficult to track down since it takes so long to reproduce.

**Comment by mvoosten** [comment] 2019-01-30 12:41
Hi thansmister, thanks for looking into it.
What I did sofar is:
1. Turn off night mode
AND
2. Turn off ambient display

So far so good.. but suspect #1 the main cause

**Comment by thanksmister** [comment] 2019-01-31 15:13
Night mode is a really heavy action, it recreates the activity and all the views to achieve the different background colors.   I suspect that when this happens, the application sometimes puts the application in the background.  I may have to add some functionality to bring the app to the foreground or reset the prevent sleep, but again, its hard to see which feature would offer a fix.

**Comment by thanksmister** [comment] 2019-04-01 23:07
I have decreased the frequency by not using the camera.  I am closing this issue as won't fix because there is no fix for this issue.  The application is closing due to the device.

**Closed by thanksmister** 2019-04-01 23:07 UTC
Labels: bug, test
